// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsComplex.Api.Data;

#nullable disable

namespace SportsComplex.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926203834_AuditoriaAsistenciaParametros")]
    partial class AuditoriaAsistenciaParametros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsComplex.Api.Entities.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_auditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("entidad");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int")
                        .HasColumnName("id_registro");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Entidad", "IdRegistro")
                        .HasDatabaseName("IX_Auditoria_Entidad_Registro");

                    b.ToTable("Auditoria", null, t =>
                        {
                            t.HasCheckConstraint("CK_Auditoria_Accion", "accion IN ('Alta','Modificación','Baja')");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Cancelacion", b =>
                {
                    b.Property<int>("IdCancelacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cancelacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCancelacion"));

                    b.Property<DateTime>("FechaCancelacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cancelacion");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("motivo");

                    b.HasKey("IdCancelacion");

                    b.HasIndex("IdReserva")
                        .IsUnique();

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cancelacion", (string)null);
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Cancha", b =>
                {
                    b.Property<int>("IdCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cancha");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCancha"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioPorHora")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_por_hora");

                    b.Property<string>("TipoSuperficie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_superficie");

                    b.HasKey("IdCancha");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Cancha", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cancha_Precio", "precio_por_hora > 0");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Devolucion", b =>
                {
                    b.Property<int>("IdDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_devolucion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevolucion"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCancelacion")
                        .HasColumnType("int")
                        .HasColumnName("id_cancelacion");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("metodo");

                    b.Property<decimal>("MontoDevuelto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_devuelto");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDevolucion");

                    b.HasIndex("IdCancelacion")
                        .IsUnique();

                    b.HasIndex("IdUsuario");

                    b.ToTable("Devolucion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Devolucion_Monto", "monto_devuelto > 0");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<string>("ContactoNombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contacto_nombre");

                    b.Property<string>("ContactoTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contacto_telefono");

                    b.Property<int>("IdTorneo")
                        .HasColumnType("int")
                        .HasColumnName("id_torneo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEquipo");

                    b.HasIndex("IdTorneo", "Nombre")
                        .IsUnique();

                    b.ToTable("Equipo", (string)null);
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Integrante", b =>
                {
                    b.Property<int>("IdIntegrante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_integrante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIntegrante"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("dni");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.HasKey("IdIntegrante");

                    b.HasIndex("IdEquipo", "Dni")
                        .IsUnique();

                    b.ToTable("Integrante", (string)null);
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("IdReferencia")
                        .HasColumnType("int")
                        .HasColumnName("id_referencia");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensaje");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdUsuario", "Tipo", "IdReferencia")
                        .IsUnique()
                        .HasDatabaseName("UX_Notificacion_Usuario_Evento")
                        .HasFilter("[id_referencia] IS NOT NULL");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdPago");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pago", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pago_Monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Parametro", b =>
                {
                    b.Property<int>("IdParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_parametro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParametro"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("valor");

                    b.HasKey("IdParametro");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Parametro", (string)null);

                    b.HasData(
                        new
                        {
                            IdParametro = 1,
                            Clave = "minutos_inactividad",
                            Descripcion = "Minutos sin actividad antes de cerrar la sesión automáticamente",
                            Valor = "30"
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Partido", b =>
                {
                    b.Property<int>("IdPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_partido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPartido"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int")
                        .HasColumnName("goles_local");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int")
                        .HasColumnName("goles_visitante");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int")
                        .HasColumnName("id_cancha");

                    b.Property<int>("IdEquipoLocal")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo_local");

                    b.Property<int>("IdEquipoVisitante")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo_visitante");

                    b.Property<int>("IdTorneo")
                        .HasColumnType("int")
                        .HasColumnName("id_torneo");

                    b.HasKey("IdPartido");

                    b.HasIndex("IdEquipoLocal");

                    b.HasIndex("IdEquipoVisitante");

                    b.HasIndex("IdTorneo");

                    b.HasIndex("IdCancha", "Fecha", "HoraInicio")
                        .IsUnique();

                    b.ToTable("Partido", null, t =>
                        {
                            t.HasCheckConstraint("CK_Partido_EquiposDistintos", "id_equipo_local <> id_equipo_visitante");

                            t.HasCheckConstraint("CK_Partido_Estado", "estado IN ('Programado','Jugado')");

                            t.HasCheckConstraint("CK_Partido_GolesLocal", "goles_local >= 0");

                            t.HasCheckConstraint("CK_Partido_GolesVisitante", "goles_visitante >= 0");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Asistencia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("asistencia");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("estado_pago");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado_reserva");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int")
                        .HasColumnName("id_cancha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdCancha", "Fecha", "HoraInicio")
                        .IsUnique()
                        .HasDatabaseName("UX_Reserva_Cancha_Fecha_Horario")
                        .HasFilter("[estado_reserva] <> 'Cancelada'");

                    b.ToTable("Reserva", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reserva_Asistencia", "asistencia IS NULL OR asistencia IN ('Presente','Ausente')");

                            t.HasCheckConstraint("CK_Reserva_EstadoPago", "estado_pago IN ('Pendiente','Parcialmente abonado','Abonado')");

                            t.HasCheckConstraint("CK_Reserva_EstadoReserva", "estado_reserva IN ('Confirmada','Pendiente','Cancelada')");

                            t.HasCheckConstraint("CK_Reserva_Horario", "hora_fin > hora_inicio");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Torneo", b =>
                {
                    b.Property<int>("IdTorneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_torneo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTorneo"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTorneo");

                    b.ToTable("Torneo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Torneo_Estado", "estado IN ('Planificado','En curso','Finalizado')");

                            t.HasCheckConstraint("CK_Torneo_Fechas", "fecha_fin >= fecha_inicio");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_Rol", "rol IN ('administrador','empleado')");
                        });
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Auditoria", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Cancelacion", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Reserva", "Reserva")
                        .WithOne("Cancelacion")
                        .HasForeignKey("SportsComplex.Api.Entities.Cancelacion", "IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Usuario", "Usuario")
                        .WithMany("Cancelaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Devolucion", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Cancelacion", "Cancelacion")
                        .WithOne("Devolucion")
                        .HasForeignKey("SportsComplex.Api.Entities.Devolucion", "IdCancelacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Usuario", "Usuario")
                        .WithMany("Devoluciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cancelacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Equipo", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Torneo", "Torneo")
                        .WithMany("Equipos")
                        .HasForeignKey("IdTorneo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Integrante", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Equipo", "Equipo")
                        .WithMany("Integrantes")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Notificacion", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Pago", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Usuario", "Usuario")
                        .WithMany("Pagos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Partido", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Cancha", "Cancha")
                        .WithMany("Partidos")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Equipo", "EquipoLocal")
                        .WithMany("PartidosLocal")
                        .HasForeignKey("IdEquipoLocal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Equipo", "EquipoVisitante")
                        .WithMany("PartidosVisitante")
                        .HasForeignKey("IdEquipoVisitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Torneo", "Torneo")
                        .WithMany("Partidos")
                        .HasForeignKey("IdTorneo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Reserva", b =>
                {
                    b.HasOne("SportsComplex.Api.Entities.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsComplex.Api.Entities.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Cancelacion", b =>
                {
                    b.Navigation("Devolucion");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Cancha", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Equipo", b =>
                {
                    b.Navigation("Integrantes");

                    b.Navigation("PartidosLocal");

                    b.Navigation("PartidosVisitante");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Reserva", b =>
                {
                    b.Navigation("Cancelacion");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Torneo", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("SportsComplex.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Cancelaciones");

                    b.Navigation("Devoluciones");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
